### ISSUE TITLE
Support nested ignore_read in Terraform

### ISSUE THREAD

**Issue by rileykarson** [GoogleCloudPlatform/magic-modules#1019]

**Comment by emilymye** [comment]
NOTE: This is deceptively difficult, as we can't just skip the flatten step for a given property. Because we are setting the top-level field in state, we still need to set the nested field value, which requires us passing down the nearest parent value in state into the flatteners. We can't do a nested d.Get check, or it would be VERY BAD  because of sets (e.g. could get something like d.Get("a_parent_field.0.a_parent_field.123456789.value")

**Comment by rileykarson** [comment]
In addition to @emilymye's comment, there's some context at https://github.com/GoogleCloudPlatform/magic-modules/pull/987 when I ran into this not working.
