### ISSUE TITLE
Add support for Cloud NAT in gcp_compute_router module of ansible

### ISSUE THREAD

**Issue by Madhura-CSI** [GoogleCloudPlatform/magic-modules#1082]
As Cloud NAT feature is available as a v1 api now, could you please add support for it in gcp_compute_router module? 
@rambleraptor, requesting you to have a look at this.

**Comment by rileykarson** [comment]
Hey @Madhura-CSI!

We're closing issues against specific tools MM generates; they should be tracked in the appropriate repo for that tool. For our Ansible integrations, that means [against the ansible/ansible repo](https://github.com/ansible/ansible/issues/new/choose). If you've already filed an issue there, that's the best way to track fixes; otherwise, by filing there it will be assigned to the right person.
