### ISSUE TITLE
The build shouldn't need to pass to generate downstreams

### ISSUE THREAD

**Issue by rileykarson** [GoogleCloudPlatform/magic-modules#1083]
Right now, we run our generation, make sure all the downstream builds pass, and then create PRs against downstreams. Instead, we should:

* Generate patches
* Create PRs
* Comments with created PRs
* Run tests, update the PR with a comment with build/test errors

That way, community contributors can see the downstreams of a generated PR, and will see detailed warnings from project-specific Travis/other CI systems. Test failures will also be surfaced instead of hiding inside Concourse.

**Comment by ndmckinley** [comment]
This was an explicit requirement of the system - the plan was, no generating any PRs until all the builds pass, because otherwise folks might break someone else's build while creating their tool's downstream.  See for instance the brief discussion here: https://github.com/GoogleCloudPlatform/magic-modules/issues/193.  I'm still inclined to believe that it's best this way.

**Comment by rileykarson** [comment]
Sure- my proposal isn't to skip the tests entirely. What if we ran the test step after `create-prs` and had that as a requirement for `merge-prs`?

**Comment by ndmckinley** [comment]
Eh, I'm a weak "no" on it right now.  I've thought "oh dang, the tests don't pass, gotta fix that so the PRs will generate" way more often than I've thought "dang, why aren't the tests passing?  If only I had it in Travis.".  The Concourse status at the bottom of the page links to detailed results about as good as Travis, and we can give community contributors access to that page through their github accounts.
