### ISSUE TITLE
Cannot create instance_template with ansible due to disk_type sending url

### ISSUE THREAD

**Issue by sharoonthomas** [GoogleCloudPlatform/magic-modules#1125]
When using `gcp_compute_instance_template` and specifying `disk_type`, the code expects an URL to be sent which is then sent to the REST API.

Code block: https://github.com/ansible/ansible/blob/a6cfdc6e63ca3392ec539532db5ff820357c31a5/lib/ansible/modules/cloud/google/gcp_compute_instance_template.py#L1067-L1073

However, the InstanceTemplate resource endpoint expects a name (not the url)

![screen shot 2018-12-30 at 6 05 27 pm](https://user-images.githubusercontent.com/305807/50552272-9272ce00-0c5d-11e9-9be4-e09649b4511e.png)

**Comment by rileykarson** [comment]
Hey @sharoonthomas!

We're closing issues against specific tools MM generates; they should be tracked in the appropriate repo for that tool. For our Ansible integrations, that means [against the ansible/ansible repo](https://github.com/ansible/ansible/issues/new/choose). If you've already filed an issue there, that's the best way to track fixes; otherwise, by filing there it will be assigned to the right person.
