### ISSUE TITLE
Magician should update pipeline in merge-prs

### ISSUE THREAD

**Issue by rambleraptor** [GoogleCloudPlatform/magic-modules#1177]

**Comment by slevenick** [comment]
Do we really want this? Shouldn't a developer update the pipeline and do some testing of if the new pipeline is correct prior to merging the PR? 

I imagine a scenario where a bad pipeline update causes the pipeline to break, and the fix cannot be merged & updated because the pipeline is broken

**Comment by rambleraptor** [comment]
I think we should have a better process in place for testing the pipeline. 

Right now, our process is:

1) Write out the new pipeline.
2) Get a +2 on the PR
3) Merge the PR
4) Update the pipeline.

We don't really test the pipeline changes until the PR is merged in. In that flow, it seems like updating the pipeline just removes a step from the process.

If we move towards:

1) Write a new pipeline
2) Update the pipeline using the not-yet-merged PR to either prod/staging + do testing.
3) If it works, get a +2 on PR.
4) Update PR.

then I could see this idea being dangerous.

**Comment by rileykarson** [comment]
@ndmckinley you decided this shouldn't be an automated step, right? Do you mind attaching (some) context on why and closing this if that's the case?

**Comment by ndmckinley** [comment]
I think that most of the time, the right move will have been to make the pipeline changes in the course of testing the changes.  That gives us two reasons not to automate it in the merge-prs step:
- Most of the time, it's not necessary to set the pipeline since it'll be set already
- Sometimes, the pipeline will be out of sync with what's at HEAD on master.  If someone is testing their changes to the pipeline, and someone else merges a PR, and the config in the merged pr is used, the test changes will be overwritten.

If people are having trouble setting the pipeline up (e.g. if fly configuration is a pain), we could easily have a separate job in the magician which was hand-triggered to update the pipeline.  What do you think about that?

**Comment by rileykarson** [comment]
So it sounds like we can close this out.
