### ISSUE TITLE
Ansible gcp_compute_network_facts docs

### ISSUE THREAD

**Issue by gundalow** [GoogleCloudPlatform/magic-modules#1423]
Looks like the docs could be improved for `gcp_compute_network_facts`
https://github.com/ansible/ansible/pull/47507

Original issue: https://github.com/ansible/ansible/issues/47499

@walterdolce

**Comment by rileykarson** [comment]
Hey @gundalow!

We're closing issues against specific tools MM generates; they should be tracked in the appropriate repo for that tool. For our Ansible integrations, that means [against the ansible/ansible repo](https://github.com/ansible/ansible/issues/new/choose). If you've already filed an issue there, that's the best way to track fixes; otherwise, by filing there it will be assigned to the right person.

**Comment by gundalow** [comment]
What about PRs, see https://github.com/ansible/ansible/pull/47507

**Comment by rileykarson** [comment]
PRs should be made here! In general, this repo needs to be the canonical source of truth for code in the [GCP plugins for] tools it supports. We have an upstreaming process for community contributions to another downstream, Terraform, that it could be worth discussing implementing for Ansible as well with @rambleraptor. Admittedly, this is primarily for Terraform's handwritten files which I don't believe MM manages many / any of for Ansible.
