### ISSUE TITLE
ansible module for granting roles to service accounts

### ISSUE THREAD

**Issue by geekq** [GoogleCloudPlatform/magic-modules#1462]
We can create a service account via `gcp_iam_service_account` module. But we need the possibility to assign roles to that account to do something useful with it. Like in terraform https://www.terraform.io/docs/providers/google/r/google_project_iam.html#google_project_iam_binding

Are there any plans to add such ansible module or do I need to extend
https://github.com/GoogleCloudPlatform/magic-modules/blob/master/products/iam/api.yaml myself?

There is plenty of magic there ;-) so for me it is unfortunately not obvious how to map the relevant Google Cloud docs https://cloud.google.com/iam/docs/granting-roles-to-service-accounts#granting_access_to_a_service_account_for_a_resource to api.yaml

**Comment by rileykarson** [comment]
Hey @geekq!

We're closing issues against specific tools MM generates; they should be tracked in the appropriate repo for that tool. For our Ansible integrations, that means [against the ansible/ansible repo](https://github.com/ansible/ansible/issues/new/choose). If you've already filed an issue there, that's the best way to track fixes; otherwise, by filing there it will be assigned to the right person.
