### ISSUE TITLE
Investigate if it is safe to send NULL for all list/set fields when they are empty

### ISSUE THREAD

**Issue by rosbo** [GoogleCloudPlatform/magic-modules#183]
Right now, we send an empty array.

Except for sslPolicy where we explicitly set `customFeatures` to `nil` (custom update encoder) when it is empty otherwise the GCP API fails:
```sh
Error updating SslPolicy "test-ssl-policy-e932gyhz3g": googleapi: Error 400: Invalid value for field 'resource.customFeatures': ''. Custom features cannot be specified when the SslPolicy profile is not 'CUSTOM', invalid
```

To validate:
- If a have resource `A` with field `b`. If `b` is a list with 1 element after creation, if I update `b` to remove the element and the server sends `nil`, does all GCP API empty `b` or do some just ignore the changes to `b` and keep all the elements.

**Comment by rileykarson** [comment]
You've been working on this right @chrisst?

**Comment by chrisst** [comment]
yeah, basically the answer is: It's not safe. Stackdriver api is a jerk about sending nil's in mutually exclusive fields. Instead of empty arrays or nil, we need to completely omit them.

For many of the rest of the apis I've noticed that they are pretty tolerant of either empty list, nil or omitting the key. So in order to please the lowest common denominator we are going to emit any empty object/array: https://github.com/GoogleCloudPlatform/magic-modules/pull/497
