### ISSUE TITLE
Terraform generated code should use provider-level config for region/zone

### ISSUE THREAD

**Issue by danawillow** [GoogleCloudPlatform/magic-modules#198]
Right now we have getProject hard-coded into the templates, but nothing for getRegion or getZone. This means our generated resources that aren't global aren't falling back to provider defaults (see https://github.com/terraform-providers/terraform-provider-google/blob/master/google/resource_compute_vpn_gateway.go)

**Comment by rosbo** [comment]
I actually works since `replaceVars` is calling getRegion/getZone inside the create method. It only works if the region or zone is part of the url (which I think is always the case). I agree this is confusing because we also send the region in the request body. We probably shouldn't send the url parameters in the request body.

**Comment by rileykarson** [comment]
Closing based on Vincent's response. [Terraform code](https://github.com/terraform-providers/terraform-provider-google/blob/master/google/transport.go#L98).
