### ISSUE TITLE
Add support to `get_content` in Ansible `gcp_storage_object`

### ISSUE THREAD

**Issue by PedDavid** [GoogleCloudPlatform/magic-modules#2427]
Similar to [gc_storage_module](https://docs.ansible.com/ansible/latest/modules/gc_storage_module.html) `get_str` mode.

Since [the recommended way of storing secrets](https://cloud.google.com/kms/docs/store-secrets) is using GCS as some kind of parameter / secret store this would be a useful use case as I wouldn't want to either leave "temporary" files behind or dealing with clean up afterwards when that's simply unnecessary.

**Comment by rileykarson** [comment]
Hey @PedDavid!

We're closing issues against specific tools MM generates; they should be tracked in the appropriate repo for that tool. For our Ansible integrations, that means [against the ansible/ansible_collections_google repo](https://github.com/ansible/ansible_collections_google/issues/new). If you've already filed an issue there, that's the best way to track fixes; otherwise, by filing there it will be assigned to the right person.
