### ISSUE TITLE
Add `tf-test` prefix to generated Terraform test data

### ISSUE THREAD

**Issue by chrisst** [GoogleCloudPlatform/magic-modules#2578]
Using `ctx` variables in examples will generate tests that have a random suffix on the values that are substituted in tests but leaves the suffix out from the user facing documentation. We should also add a prefix to this substitution so that tests generate data that can be easily filtered for sweepers but the prefix should not be included in the documentation.

**Comment by chrisst** [comment]
This is currently possible using [`substitute_test_path`](https://github.com/GoogleCloudPlatform/magic-modules/blob/master/provider/terraform/examples.rb#L190) but leaving this open as it's a bit convoluted right now and could be improved.

**Comment by rileykarson** [comment]
That's just the path to find constant data files at for things like Cloud Functions. This change would be easy enough, https://github.com/GoogleCloudPlatform/magic-modules/blob/master/provider/terraform/examples.rb#L144 just needs to be set to:

```ruby
vars: vars.map { |k, str| [k, "tf-test-#{str}%{random_suffix}"] }.to_h,
```

I think I used a suffix originally because the random value may start with a number, which isn't valid for GCP names.

**Comment by rileykarson** [comment]
Closed by @emilymye in https://github.com/GoogleCloudPlatform/magic-modules/pull/3072
