### ISSUE TITLE
Creates context level enforcing corporate device.

### ISSUE THREAD

**Issue by mikhail-khodorovskiy** [GoogleCloudPlatform/magic-modules#2708]
How do I setup a condition for https://cloud.google.com/access-context-manager/docs/access-level-attributes#require-corp-owned-device?

```
conditions {
      device_policy {
         require_corp_owned = true
      }
    }
```
on google beta provider 2.20.0 response with "An argument named "require_corp_owned" is not expected here."

**Comment by danawillow** [comment]
Hi @mikhail-khodorovskiy, since this feature request is Terraform-specific, can you please use the Terraform issue tracker instead? https://github.com/terraform-providers/terraform-provider-google/issues. That helps us keep all our feature requests for each product in a predictable place, and lets us use this one for core magic modules feature tracking.
