### ISSUE TITLE
Ansible modules are not idempotent

### ISSUE THREAD

**Issue by lubo** [GoogleCloudPlatform/magic-modules#394]
I've been trying out `gcp_container_cluster` and `gcp_container_node_pool` Ansible modules and I've noticed that they are not idempotent. For example, when I disable `http_load_balancing` on an existing cluster or change management parameters on an existing node pool, the resources (clusters and node pools) are not updated. In my opinion, this is not the desired behavior when using declarative configuration management. Is it really supposed to work this way? Any plans on changing it?

**Comment by rambleraptor** [comment]
Thanks a lot for bringing this to my attention! This is definitely not expected behavior on the modules. `http_load_balancing` in particular has a slightly different update API than the rest of container_clusters. We've got support for adding these new update APIs on Magic Modules now.

I'll definitely get this fixed very soon. Thanks again and let me know if you see any other issues!

**Comment by lubo** [comment]
Good to hear that. Do you have any time estimates? I'm currently in process of migrating our company infrastructure to cloud and this is a show-stopper for me.

**Comment by lubo** [comment]
@rambleraptor Anything new?
