### ISSUE TITLE
Missing parameters in gcp_container_cluster Ansible module

### ISSUE THREAD

**Issue by lubo** [GoogleCloudPlatform/magic-modules#398]
When compared to `container.v1.cluster` resource in Cloud Deployment Manager, `gcp_container_cluster` Ansible module is missing several configuration parameters. This is a short list of the parameters that are missing and that we consider essential:

* [`addons_config.kubernetes_dashboard`](https://cloud.google.com/kubernetes-engine/docs/reference/rest/v1/projects.zones.clusters#AddonsConfig.FIELDS.kubernetes_dashboard)
* [`initial_cluster_version`](https://cloud.google.com/kubernetes-engine/docs/reference/rest/v1/projects.zones.clusters#Cluster.FIELDS.initial_cluster_version)
* [`maintenance_policy`](https://cloud.google.com/kubernetes-engine/docs/reference/rest/v1/projects.zones.clusters#Cluster.FIELDS.maintenance_policy)
* [`network_policy`](https://cloud.google.com/kubernetes-engine/docs/reference/rest/v1/projects.zones.clusters#Cluster.FIELDS.network_policy)
* [`node_pools`](https://cloud.google.com/kubernetes-engine/docs/reference/rest/v1/projects.zones.clusters#Cluster.FIELDS.node_pools)

Any plans on adding these?

**Comment by rileykarson** [comment]
Hey @lubo!

We're closing issues against specific tools MM generates; they should be tracked in the appropriate repo for that tool. For our Ansible integrations, that means [against the ansible/ansible repo](https://github.com/ansible/ansible/issues/new/choose). If you've already filed an issue there, that's the best way to track fixes; otherwise, by filing there it will be assigned to the right person.
