### ISSUE TITLE
Add Ansible facts modules fo container

### ISSUE THREAD

**Issue by lubo** [GoogleCloudPlatform/magic-modules#433]
I've tried to generate the modules myself, but `gcp_container_cluster_facts` doesn't work because `https://container.googleapis.com/v1/projects/{projectId}/zones/{zone}/clusters` doesn't have `filter` parameter. Why do these modules use `list` methods anyway?

**Comment by rambleraptor** [comment]
Hello! We've since added a `gcp_container_cluster_facts` module! https://github.com/ansible/ansible/pull/48249

We're currently waiting on Ansible to merge it in.

To answer your question, we use the `list` methods to get a list of resources to return. Any client libraries or other methods will probably call the `list` REST method to gain information about multiple resources at once.

**Comment by rambleraptor** [comment]
These have been merged in!
