### ISSUE TITLE
Docs: Clarify difference between property and parameter

### ISSUE THREAD

**Issue by danawillow** [GoogleCloudPlatform/magic-modules#53]
From https://github.com/GoogleCloudPlatform/magic-modules/blob/master/DEVELOPER.md#resource---parameters--properties-:
> The main difference between a parameter and a property is that a parameter is not part of the object, and will be used by the user to convey data to the generated code, usually to help locate the object. Every property will be eventually persisted as fields of the remote object in GCP.

My reading of this is that when you create a GCP object, parameters are things that would be passed into the URL of the API call (like `region` or `zone`), whereas properties are things that are set on the resource itself. However, this doesn't seem to always hold true- `diskEncryptionKey` (on the disk resource) is marked as a parameter, but is set on create. It can't be modified, so it's set as `input: true`, but `zone` also can't be updated and it doesn't have that marking. It would be great to have a bit more expansion in the docs of when to use property vs parameter and how it interacts with `input: true`.

**Comment by nelsonjr** [comment]
A parameter is something used to create (or edit) the object that is not part of the object integrity checks. Sometimes you have a parameter that will guide the creation, e.g. in ServiceAccountKey we have a `path` that indicates the _local file_ to write the key to. That parameter is not to be used to check against API "diffs" to see if the object changed. That also holds true for "write only" properties, such as private keys or passwords.

The reason zone does not have `input: true` is because it is required to be part of the object to begin with.

Does the above help?

**Comment by danawillow** [comment]
That distinction between parameters and properties helps, thanks. I still don't understand the zone input though, can you clarify? The docs just say:
> input: true|false indicating if the field will be used as "input", which means that the field will be used only during the creation of the object
I've been reading this as "the field is used during create, but not update", but it sounds like there might be more places where the field _could_ be used besides create and update. Is that what you're getting at?
