### ISSUE TITLE
magic-module support for swagger or openapi input?

### ISSUE THREAD

**Issue by JonKohler** [GoogleCloudPlatform/magic-modules#61]
Hey guys - first, fantastic project, really exciting stuff. 

Was wondering if its possible, practical, or planned to have the api.yaml here come from a swagger/openAPI definition.

We've modeled our APIs that way, and having THIS project would be an absolute godsend, that I'd throw all of my weight behind if we could do that

Even a sane way to convert from one to the other would be a-ok with me, so that I dont have to maintain TWO sets of API contracts, one for swagger/openapi and another for api.yaml for magic-modules, as that then leaves easy room for regressions.

Thoughts?

Thanks,
Jon

**Comment by nelsonjr** [comment]
Hi Jon,

Thanks for the kind words. I hope this would be useful to the community!

Before we went out and invented ourselves a new description (api.yaml) we looked into swagger 1.x and 2.x as well as Google Discovery. The main issue we stumbled across is that such API descriptions are for, well, APIs and not for idempotent objects. Note that api.yaml does not really describe the API, but actually API but the objects and their relationships. (grant you that api.yaml was a poor choice of name in retrospect)

In our early experiments and proof-of-concepts we even created a swagger => MM and discovery => MM, but the technical challenges that have risen due to these distinct goals made it impractical, so we threw it away.

(I'd love to not have to copy/paste from Google Discovery [or API Reference] the fields, but we ended up doing that anyway because we could make a stronger description of the objects that may -- or may not -- align with the API developers "view of the world")

**Comment by JonKohler** [comment]
Would it be possible to simply nest the structures of API.yaml in a vendor extension in swagger/openapi, such that you could JSON reference areas of the paths/parameters/definitions that were reusable?

**Comment by nelsonjr** [comment]
It seems I cannot see the benefit as the description of _target_ objects are distinct. Do you have a simple example to share so we can continue from there?

**Comment by nelsonjr** [comment]
@JonKohler friendly ping.

**Comment by erjohnso** [comment]
Hi @JonKohler - Nelson has switched projects and I think did a good job explaining why we felt it necessary to pursue a different path than Swagger. I'm closing the issue, since we're even more convinced this path works well for idempotent management of GCP resources (versus modeling our APIs) considering we're now generating assets for Chef, Puppet, Ansible, and Terraform.

Happy to keep the dialog going if you have more thoughts or examples.
